theme: jekyll-theme-minimal
title: Gusti's homepage
description: Welcome to my IT Service Management (ITSM) journey! Think of it as my digital 'home,' where I share my progress and growth throughout this course. This journey is a collection of all the assignments, labs, reflections, and projects I've completed over the semester. Each milestone represents a 'room' in my house, reflecting a different aspect of my development in the world of IT Service Management.
